# Generated by Django 3.2.12 on 2022-07-29 09:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentium_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(max_length=32)),
                ('ledger_system', models.CharField(max_length=255)),
                ('ledger_asset_id', models.IntegerField()),
                ('quantity_precision', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
                ('total_supply', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calendar_id', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=10)),
                ('market_open', models.CharField(max_length=5)),
                ('market_close', models.CharField(max_length=5)),
                ('trading_days', models.JSONField()),
                ('holidays', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'calendar',
                'verbose_name_plural': 'calendars',
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id_broker', models.IntegerField()),
                ('instrument_id_exchange', models.IntegerField()),
                ('symbol', models.CharField(blank=True, default=None, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code="Invalid instrument's name", message='Instrument must be 0-9,- and (.)', regex='^[A-Za-z0-9.-]*$')])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('quote_currency', models.CharField(max_length=8)),
                ('order_flow', models.CharField(default='Fully Collateralized Internally', max_length=255)),
                ('trade_flow', models.CharField(default='External & Internal', max_length=255)),
                ('image_urls', models.JSONField(blank=True)),
                ('price_precision', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('quantity_precision', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('min_quantity', models.FloatField()),
                ('max_quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_asset', to='authentium_market.asset', to_field='asset_id')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentium_market.calendar')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_asset', to='authentium_market.asset', to_field='asset_id')),
            ],
        ),
    ]
