# Generated by Django 3.2.12 on 2022-07-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentium_market', '0002_asset_calendar_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], max_length=200)),
                ('ledger_system', models.CharField(max_length=200)),
                ('ledger_account_id', models.CharField(max_length=200)),
                ('comp_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(to='authentium_market.Asset')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'permission',
            },
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'instrument', 'verbose_name_plural': 'instruments'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='base_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_asset', to='authentium_market.asset'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='quote_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_asset', to='authentium_market.asset'),
        ),
        migrations.AlterModelTable(
            name='instrument',
            table='instrument',
        ),
        migrations.CreateModel(
            name='TradingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taker_fee', models.IntegerField(default=0)),
                ('maker_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentium_market.instrument')),
            ],
            options={
                'verbose_name': 'trading_fee',
                'verbose_name_plural': 'trading_fees',
                'db_table': 'trading_fee',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentium_market.account')),
                ('permissions', models.ManyToManyField(to='authentium_market.Permission')),
            ],
            options={
                'verbose_name': 'trader',
                'verbose_name_plural': 'traders',
                'db_table': 'trader',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_type', models.CharField(choices=[('Limit', 'Limit'), ('Market', 'Market')], max_length=10)),
                ('side', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('time_in_force', models.CharField(choices=[('GTC', 'Gtc'), ('GTD', 'Gtd'), ('FOK', 'Fok'), ('IOC', 'Ioc')], max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentium_market.account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentium_market.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='fees',
            field=models.ManyToManyField(to='authentium_market.TradingFee'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.FloatField(default=0)),
                ('locked', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentium_market.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentium_market.asset')),
            ],
            options={
                'verbose_name': 'balance',
                'verbose_name_plural': 'balances',
                'db_table': 'balance',
                'unique_together': {('account', 'asset')},
            },
        ),
    ]
