# Generated by Django 3.2.12 on 2022-07-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentium_market', '0003_auto_20220729_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='calendar',
            new_name='calendar_ins',
        ),
    ]
