# Generated by Django 3.2.12 on 2022-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentium_market', '0004_rename_calendar_instrument_calendar_ins'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='trader_id',
            field=models.CharField(default=None, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
