# Generated by Django 3.2.12 on 2022-07-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentium_market', '0006_auto_20220729_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AddField(
            model_name='trader',
            name='password',
            field=models.CharField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
