# Generated by Django 3.2.12 on 2022-07-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentium_market', '0007_auto_20220730_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(choices=[('Admin', 'Admin'), ('Trader', 'Trader')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'token',
                'db_table': 'token',
            },
        ),
    ]
