from enum import Enum


class AssetStatus(Enum):
    ACTIVE = "Active"
    DISABLED = "Disabled"


ASSET_NAME_MAX_LENGTH = 8
ASSET_DESCRIPTION_MAX_LENGTH = 32
QUANTITY_PRECISION_MIN = 0
QUANTITY_PRECISION_MAX = 6
TOTAL_SUPPLY_MIN = 1
PAGE_DEFAULT = 1
DATA_PER_PAGE_DEFAULT = 10
NEBULA_TRADER_EXISTS = 80000
NEBULA_ACCOUNT_EXISTS = 102

INSTRUMENT_DESCRIPTION_MAX_LENGTH = 1000
INSTRUMENT_SYMBOL_MAX_LENGTH = 16
ORDER_FLOW_DEFAULT = "Fully Collateralized Internally"
TRADE_FLOW_DEFAULT = "External & Internal"
